### ISSUE TITLE
pip install pybeagle command error 

### ISSUE THREAD

**Issue by alishasonawalla** [yampelo/beagle#14]
When I tried to run the command `pip install pybeagle` to install pybeagle as a library, I got the following error: 

`Could not find a version that satisfies the requirement pybeagle (from versions: )
No matching distribution found for pybeagle`

I'm currently trying to install pybeagle on a MacOS Mojave, with Python 3.7.1. I also tried to run the command on another Mac OS Mojave machine with Python 2.7.15 and with Ubuntu WSL on Windows 10 with Python 2.7.15 and encountered the same issue. 

Any idea why that might be the case? - Thanks!

**Comment by yampelo** [comment]
Try and use Python3.6, Python3.7 doesn't work because of issues with `rekall` (https://github.com/google/rekall/issues/488) once they unpin the version of acora to the version which has the ability to compile CPython code for 3.7, i'll add the ability to install on 3.7

**Comment by alishasonawalla** [comment]
Was still running into issues with Python 3.6, but I see you have a PR with a fix open! Thank you :)

**Comment by yampelo** [comment]
You should be able to install now if you are using windows, i've set up testing and fixed all issues preventing it from being installed: https://travis-ci.com/yampelo/beagle/builds/107562330
