### ISSUE TITLE
Documentation/Installing: docker run issue?

### ISSUE THREAD

**Issue by carlyabraham** [yampelo/beagle#2]
For reference:
- Operating System: Ubuntu WSL on Windows 10
- Docker Installation: Ubuntu docker installation but running daemon from Docker for Windows, as per [this guide](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly)

I've been going through the installation, and seem to have come across an issue with the docker run command. The command from the docs is: 
`docker run -v "data/beagle":"/data/beagle" -p 8000:8000 beagle`

The error I received was:
```
Unable to find image 'beagle:latest' locally
docker: Error response from daemon: pull access denied for beagle, repository does not exist or 
may require 'docker login'.
See 'docker run --help'.
```
Looking at my images list, it seems that beagle is listed under "yampelo/beagle":
![Capture](https://user-images.githubusercontent.com/17581510/54947428-ac484800-4f10-11e9-92ec-c00b6d484c80.PNG)

Without running `docker pull` again, I was able to get `docker run` to work by making the path the same for the volume mount, and changing the image name:
`docker run -v "/data/beagle":"/data/beagle" -p 8000:8000 yampelo/beagle`

I'm not sure if this indicates a general installation issue, or if my using WSL creates this problem, though I'd bet the latter. Any insight on this would be great, thanks!

**Comment by williballenthin** [comment]
based on my limited experience with docker, I believe this is an issue with the instructions in the readme. I think that you are correct that you'll have to reference the image locally as `yampelo/beagle`. i've opened #3  to address this issue.
