### ISSUE TITLE
Update to installation guide 

### ISSUE THREAD

**Issue by alishasonawalla** [yampelo/beagle#20]
While going through the recent PR and issue conversation, I realized that it might be helpful to update the installation guidelines with the following:

1. Only Python 3.6 is currently supported: ref https://github.com/yampelo/beagle/pull/5 https://github.com/yampelo/beagle/issues/14
2. Rekall can be installed as an extra using `pip install pybeagle[rekall]` ref: https://github.com/yampelo/beagle/pull/19

Let me know if this is alright. If so, I can make a PR for the issue. 

Thanks!

**Comment by yampelo** [comment]
go for it

**Comment by alishasonawalla** [comment]
Thanks!
