### ISSUE TITLE
Double Byte in HX Triage file support?

### ISSUE THREAD

**Issue by nicholashsiao** [yampelo/beagle#32]
Hi,
HX triages files from double byte windows (Chinese Windows).
Beagle show me the following errors while I upload the .mans file.

Error on parse: 'utf-8' codec can't decode byte 0x87 in position 16: invalid start byte

Regards,
Nicholas

**Comment by yampelo** [comment]
Can you post the full traceback/error from the container or library? i want to see which function is throwing this

**Comment by nicholashsiao** [comment]
I am sorry, it works now. I think I selected wrong data type.

**Comment by yampelo** [comment]
it happens! that’s why i was trying to figure out exactly which call it was, since i was using utf-8 when opening the files in the triage.
