### ISSUE TITLE
Right report format for FireEye AX?

### ISSUE THREAD

**Issue by okkesozdemir** [yampelo/beagle#36]
Hi,

Couldn't find a way to upload a correct AX report. I generated all kinds of report from FireEye AX, but none seems to be correct. FireEye AX reports may be concise/normal/extended in detail and xml, json, text and csv in format. Which is the correct one to upload to beagle?

And thank you very much for this great work!

Best regards,

**Comment by yampelo** [comment]
extended + json should work.

**Comment by okkesozdemir** [comment]
Sorry, 

Error
Error on parse: time data '2019-05-07T02:04:36Z' does not match format '%Y-%m-%d %H:%M:%S'

Changing time slot from past-day to past-week etc doesn't differ. My AX version is 8.2.0

**Comment by yampelo** [comment]
I'm going to add support for that date format, but it would be easiest if you can send me the exported report (if it's alright with you) so that I can make sure that no other formatting changed.

**Comment by yampelo** [comment]
@okkesozdemir  I added your format string to https://github.com/yampelo/beagle/pull/37/files, if you aren't comfortable sending me a sample AX report then let me know and i'll merge this change in and you can try again after pulling down the docker container :)

**Comment by okkesozdemir** [comment]
Unfortunately I can not share a full report but a simple part of it as below:

{"msg": "extended", "product": "MAS", "version": "8.2.0.784037", "appliance": "", "appliance-id": "",
"alert": [
{
  "src": {
    "url": "2cdfc99631e3517a457920f6ee64d52a.zip"
  }, 
  "severity": "majr", 
  "alert-url": "", 
  "ack": "no", 
  "explanation": {
    "malware-detected": {
      "malware": {
        "profile": "centos-7.2", 
        "executed-at": "2019-05-07T02:04:36Z", 
        "sha1": "4e86d2f7485e95a923438acea8db1759441bf09c", 
        "name": "Malware.archive", 
        "downloaded-at": "2019-05-07T02:04:36Z", 
        "application": "explorer", 
        "sha512": "653fe52919856eb9116605fec97692d2c69698e4573c71206a4050b25bc4bb41fd6c79e8f3e49e9d386eb13fd3c028151188a9960c1280410b07c43dcff619fc", 
        "malicious": "yes", 
        "note": "", 
        "sha256": "4f9167bbc080109ad728e365474476f88446ef24f7cfc0f606d79766cf4e488c", 
        "submitted-at": "2019-05-07T02:04:11Z", 
        "user": "", 
        "md5sum": "e5e4256a017c64b68850a40390f06e42", 
        "type": "zip", 
        "original": "2cdfc99631e3517a457920f6ee64d52a.zip", 
        "stype": "archive"
      }
    },

**Comment by yampelo** [comment]
@okkesozdemir try now, do `docker pull yampelo/beagle:latest` and re-run the container

**Comment by okkesozdemir** [comment]
Hi,

This time :(

Set up FireEyeAX Report
2019-05-08T15:26:16 | beagle.web.api.views.new:293 | CRITICAL | Failure to generate graph 'alertUrl'

**Comment by yampelo** [comment]
I have an idea, do you wanna submit something publicly available (maybe even a dummy test binary) and privately message the report on slack or over e-mail or something? I just need something in the new 8.2.0 format

**Comment by okkesozdemir** [comment]
Please give me an email address (or any other means you wish) to send the json to.

**Comment by yampelo** [comment]
yampelo@umd.edu

**Comment by okkesozdemir** [comment]
Sent

**Comment by yampelo** [comment]
I didn't get it, im guessing my universities e-mail protection flagged it. try my personal email (omeryample$at$gmail.com)

**Comment by okkesozdemir** [comment]
omeryample at gmail seems to be wrong, I sent to omeryampel at gmail. Also to your university email address as a encrypted zip. Zip password is Yampel

**Comment by yampelo** [comment]
Got it! It looks like a lot of the field names changed between 8.1 and 8.2 but I think I spotted most of them, im gonna take this chance to make the AX report data source aware, i'll push the fixes hopefully by the end of tomorrow.

**Comment by yampelo** [comment]
Here's the amound of nodes it found from the JSON you sent me, gonna write a few tests tomorrow and merge it.

```
2019-05-09T23:42:14 | beagle.transformers.base_transformer.run:111 | INFO | Finished processing of events, created 42 nodes.
2019-05-09T23:42:14 | beagle.backends.networkx.__init__:51 | INFO | Initialized NetworkX Backend
2019-05-09T23:42:14 | beagle.backends.networkx.graph:65 | INFO | Beginning graph generation.
2019-05-09T23:42:14 | beagle.backends.networkx.graph:71 | INFO | Completed graph generation.
2019-05-09T23:42:14 | beagle.backends.networkx.graph:72 | INFO | Graph contains 18 nodes and 31 edges.
```

**Comment by okkesozdemir** [comment]
Great, looking forward to see!

**Comment by yampelo** [comment]
I merged the changes in. Just make sure you remember that the graph is generated on the first report in the alerts array in the JSON. I'm going to come up with a way / create a helper to generate multiple graphs (1 per alert) from a CMS/AX json report.
