### ISSUE TITLE
Dockerless install instructions

### ISSUE THREAD

**Issue by DigiAngel** [yampelo/beagle#8]
Subject :)  Would love to try and get this to run without docker..thank you.

**Comment by yampelo** [comment]
Try this:

```
pip install pipenv
pipenv install
cd beagle/web/static
npm install && npm audit fix
npm run build
```

This should properly install everything, at this point, create the directory you want to store data into. I generally use `/data/beagle`.  Go into `beagle/config/config_templates.cfg` and change the paths of `dir` and `database` to reflect the storage directory.

For example, if i want to use `/opt/beagle/data/` i would have the following:

```
[storage]
dir = /opt/beagle/data/
database = sqlite:////opt/beagle/data/beagle.db
```

Now, go back to the root folder of the repository and run the webserver like this

```
pipenv run gunicorn --bind 0.0.0.0:8000 -w 12 --timeout 500 beagle.web.wsgi:app
```

**Comment by DigiAngel** [comment]
Thank you!

**Comment by garanews** [comment]
I am having an issue during npm run build:

> react-scripts-ts build

Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:10927) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:10927) DeprecationWarning: Pass resolveContext instead and use createInnerContext
(node:10927) DeprecationWarning: Resolver: The callback argument was splitted into resolveContext and callback.
(node:10927) DeprecationWarning: Resolver#doResolve: The type arguments (string) is now a hook argument (Hook). Pass a reference to the hook instead.
Failed to compile.

/opt/beagle/beagle/web/static/src/views/Upload.tsx
ERROR in /opt/beagle/beagle/web/static/src/views/Upload.tsx(318,33):
TS2322: Type 'DataSourceEntry' is not assignable to type 'string | number | boolean | (string | number | boolean)[] | undefined'.
  Type 'DataSourceEntry' is missing the following properties from type '(string | number | boolean)[]': length, pop, push, concat, and 26 more.

**Comment by yampelo** [comment]
Make sure you install the same version of typescript as defined in `package.json`
